### ISSUE TITLE
Change poll titles to the date they close

### ISSUE THREAD

**Issue by Mandily** [StemboltHQ/keg_picker#53]
Polls are currently numbered. Change them to be the poll closing date to be more useful.
<img width="983" alt="poll 1" src="https://cloud.githubusercontent.com/assets/15271353/14004059/a0fb5daa-f114-11e5-8fcd-1498506f7c43.png">

**Comment by graygilmore** [comment]
I'm happy to keep the number. I'd like to see the information that you've mentioned below. You could have some simple stats:

Poll closed: #{some date}
Poll was open for: #{number} days
Votes: #{number of votes}

**Comment by Mandily** [comment]
If we're going to keep the number, then I'd also like to include it in the history table, else there's no correlation between the parent and detail view.

We could include those three data points above in the table too. There's room.

**Comment by graygilmore** [comment]
The room is tight for admins. I'd like to see this issue focus on the `#show` and we can create a different one to fix the `#index`, it'll need some love, too.

**Comment by adammathys** [comment]
Can I comment?
